#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-06-08
 */

require_once __DIR__ . '/../vendor/autoload.php';

$factory    = new \Net\Bazzline\Component\Database\FileStorage\Storage\StorageFactory();
$storage    = $factory->create();
$path       = __DIR__ . '/storage';

$storage->injectPath($path);

$collection = $storage->readMany();
$filterById = null;
$iterator   = 0;

foreach ($collection as $id => $data) {
    //we want to fetch the second id
    if ($iterator < 2) {
        $filterById = $id;
    }
    ++$iterator;
}

if (is_null($filterById)) {
    echo 'no data available in "' . $path . '"' . PHP_EOL;
} else {
    echo 'number of entries: ' . $iterator . PHP_EOL;
    echo 'deleting id "' . $filterById . PHP_EOL;
    echo PHP_EOL;

    $storage->filterById($filterById);
    if ($storage->delete()) {
        echo 'deletion was successful' . PHP_EOL;
        echo 'dumping data ...' . PHP_EOL;
        echo PHP_EOL;
        $collection = $storage->readMany();
        foreach ($collection as $id => $data) {
            echo $id . ': ' . var_export($data, true) . PHP_EOL;
        }
    } else {
        echo 'update was not successful' . PHP_EOL;
    }
}
