#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-06-08
 */

require_once __DIR__ . '/../vendor/autoload.php';

$factory    = new \Net\Bazzline\Database\FileStorage\RepositoryFactory();
$storage    = $factory->create();
$path       = __DIR__ . '/storage';

$storage->injectPath($path);
$iterator   = 0;
$collection = $storage->read();

foreach ($collection as $id => $data) {
    ++$iterator;
}

$limit = ($iterator >= 3) ? 2 : (($iterator >= 2) ? 1 : 0);

if ($limit === 0) {
    echo 'not enough data available in "' . $path . '"' . PHP_EOL;
} else {
    echo 'Number of entries: ' . $iterator . PHP_EOL;
    echo 'Limit is set to "' . $limit . '"' . PHP_EOL;
    echo PHP_EOL;
    $storage->limitBy($limit);
    $collection = $storage->read();
    foreach ($collection as $id => $data) {
        echo $id . ': ' . var_export($data, true) . PHP_EOL;
    }
}
