#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-06-08
 */

require_once __DIR__ . '/../vendor/autoload.php';

$factory    = new \Net\Bazzline\Database\FileStorage\RepositoryFactory();
$storage    = $factory->create();
$path       = __DIR__ . '/storage';

$storage->injectPath($path);

$collection = $storage->read();
$filterById = null;
$iterator   = 0;

foreach ($collection as $id => $data) {
    //we want to fetch the second id
    if ($iterator < 2) {
        $filterById = $id;
    }
    ++$iterator;
}

if (is_null($filterById)) {
    echo 'no data available in "' . $path . '"' . PHP_EOL;
} else {
    $data = array(
        'foo'   => 'bar',
        'bar'   => 'foo',
        'baz'   => date('Y-m-d H:i:s')
    );
    echo 'number of entries: ' . $iterator . PHP_EOL;
    echo 'updating id "' . $filterById . '" with "' . var_export($data, true) . PHP_EOL;
    echo PHP_EOL;

    $storage->filterById($filterById);
    if ($storage->update($data)) {
        echo 'update was successful' . PHP_EOL;
        echo 'dumping data ...' . PHP_EOL;
        echo PHP_EOL;
        $collection = $storage->read();
        foreach ($collection as $id => $data) {
            echo $id . ': ' . var_export($data, true) . PHP_EOL;
        }
    } else {
        echo 'update was not successful' . PHP_EOL;
    }
}
